const express = require('express');
const router = express.Router({ mergeParams: true });
const crypto = require('crypto');
const Case = require('../models/Case');
const Session = require('../models/Session');
const AuditLog = require('../models/AuditLog');
const { decrypt } = require('../utils/encryption');

// ──────────────────────────────────────────────
//  GET /api/cases/:caseId/export/json-ld
//  Standardised evidence export for inter-agency sharing
// ──────────────────────────────────────────────
router.get('/json-ld', async (req, res) => {
  try {
    const caseId = decodeURIComponent(req.params.caseId);

    const caseData = await Case.findOne({ caseId });
    if (!caseData) return res.status(404).json({ error: 'Case not found.' });

    const sessions = await Session.find({ caseId }).sort({ timestamp: 1 });

    // Decrypt all deposits
    const deposits = [];
    sessions.forEach((s, sIdx) => {
      s.deposits.forEach(d => {
        let content;
        try { content = decrypt(d.content); }
        catch { content = '[Decryption failed]'; }

        deposits.push({
          '@type': 'DigitalDocument',
          identifier: d._id.toString(),
          text: content,
          additionalType: d.sensoryTag,
          dateCreated: d.addedAt?.toISOString(),
          sessionIndex: sIdx + 1,
          associatedMedia: (d.attachments || []).map(a => ({
            '@type': 'MediaObject',
            name: a.originalName,
            encodingFormat: a.mimeType,
            contentUrl: a.url,
            contentSize: a.size,
            dateCreated: a.exifDate || null,
          })),
        });
      });
    });

    // Build JSON-LD document
    const jsonLd = {
      '@context': {
        '@vocab': 'https://schema.org/',
        'prama': 'https://prama.info/schema/',
      },
      '@type': 'LegalCase',
      identifier: caseId,
      name: `Case: ${caseData.clientName}`,
      dateCreated: caseData.createdAt?.toISOString(),
      status: caseData.status,
      'prama:clientName': caseData.clientName,
      'prama:hearingDate': caseData.hearingDate?.toISOString() || null,
      'prama:jurisdiction': caseData.baseLayer?.jurisdiction || null,
      'prama:baseLayer': {
        knownWindow: caseData.baseLayer?.knownWindow || null,
        anchorDays: caseData.baseLayer?.anchorDays || null,
        environmentalContext: caseData.baseLayer?.environmentalContext || null,
        medicalHistory: caseData.baseLayer?.medicalHistory || null,
      },
      'prama:sessionCount': sessions.length,
      'prama:depositCount': deposits.length,
      'prama:deposits': deposits,
      'prama:exportMetadata': {
        exportedAt: new Date().toISOString(),
        exportedBy: 'Prama Legal Workspace v1.0',
        format: 'JSON-LD (Schema.org LegalCase)',
        languageCertification: {
          interfaceLanguage: 'Hindi / English (bilingual)',
          outputLanguage: 'English',
          note: 'This export was generated by Prama Legal Workspace. The capture interface supports Hindi for accessibility. All legal output and evidence records are maintained in English. Original memory deposits are preserved in their source language.',
        },
      },
    };

    // SHA-256 integrity hash of the entire export
    const exportString = JSON.stringify(jsonLd);
    const integrityHash = crypto.createHash('sha256').update(exportString).digest('hex');

    jsonLd['prama:integrityHash'] = integrityHash;

    // Audit log
    await AuditLog.create({
      caseId,
      action: 'EXPORT_JSON_LD',
      actor: 'Lawyer',
      details: { depositCount: deposits.length, integrityHash },
      ipAddress: req.ip,
    });

    res.setHeader('Content-Type', 'application/ld+json');
    res.setHeader('Content-Disposition', `attachment; filename="${caseId}_evidence_export.jsonld"`);
    res.json(jsonLd);

  } catch (err) {
    console.error('[EXPORT] JSON-LD error:', err);
    res.status(500).json({ error: 'Export failed.', details: err.message });
  }
});

module.exports = router;
